# Generated by Django 4.1.4 on 2022-12-31 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digitial',
            new_name='digital',
        ),
    ]
