# Generated by Django 4.1.4 on 2022-12-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_digitial_product_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(default='', max_length=200),
        ),
    ]
